Repository io2-2022-JKL/team_L_frontend, pull requests merged in 2022-04, with the labels that each got.

#7 #27 & #28 patient and doctor list (fetch needs to be later updated)
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/components/Table.js
  src/components/columnsDoctors.js
  src/components/columnsPatient.js
  src/components/table.css
  src/pages/admin/loged/Doctorlist/AdminDoctorList.js
  src/pages/admin/loged/adminLogged.js
  src/pages/admin/loged/adminLogged.module.css
  src/pages/admin/loged/pacientList/AdminPacientList.js
  src/pages/admin/login/LoginAdmin.js
  src/pages/admin/navigator/adminNavigation.js
  src/pages/admin/navigator/adminNavigation.module.css
Labels: done

#8 23 patient list
  src/App.js
  src/components/EditPatientModal.js
  src/components/Modal.module.css
  src/components/columnsDoctors.js
  src/pages/TestPage.js
  src/pages/admin/loged/pacientList/AdminPacientList.js
Labels: review me

#10 56 doctors data (wrong branch name)
  src/components/DataDoctorsModal.js
  src/pages/admin/loged/Doctorlist/AdminDoctorList.js
Labels: review me

#11 added patient info
  src/components/DataPatientModal.js
  src/pages/admin/loged/pacientList/AdminPacientList.js
Labels: mergable

#12 connect front with back
  src/Services.js
  src/pages/admin/loged/Doctorlist/AdminDoctorList.js
  src/pages/admin/loged/pacientList/AdminPacientList.js
  src/pages/pacient/registration/RegistrationPacient.js
Labels: mergable

#15 Fix actions bugs
  src/components/EditDoctorModal.js
  src/components/EditPatientModal.js
  src/forms/RegistrationPacientForm.js
  src/pages/admin/loged/Doctorlist/AdminDoctorList.js
  src/pages/admin/loged/pacientList/AdminPacientList.js
  src/pages/pacient/registration/RegistrationPacient.js
Labels: done

#14 Dev
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/Services.js
  src/components/DataDoctorsModal.js
  src/components/DataFormerAppointment.js
  src/components/DataPatientModal.js
  src/components/EditDoctorModal.js
  src/components/EditPatientModal.js
  src/components/Modal.module.css
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/Table.js
  src/components/__tests__/AdminDoctorList.test.js
  src/components/__tests__/AdminNavigator.test.js
  src/components/__tests__/AdminPatientList.test.js
  src/components/__tests__/DoctorAppointmentList.test.js
  src/components/admin/SidebarData.js
  src/components/doctor/SidebarData.js
  src/components/patient/SidebarData.js
  src/components/table.css
  src/forms/AuthorizationForm.module.css
  src/forms/LoginForm.js
  src/forms/RegistrationPatientForm.js
  src/pages/admin/loged/Doctorlist/AdminDoctorList.js
  src/pages/admin/loged/adminLogged.js
  src/pages/admin/loged/adminLogged.module.css
  src/pages/admin/loged/patientList/AdminPatientList.js
  src/pages/admin/login/LoginAdmin.js
  src/pages/doctor/logged/appointmentList/DoctorAppointmentList.js
  src/pages/doctor/logged/doctorLogged.js
  src/pages/doctor/logged/doctorLogged.module.css
  src/pages/doctor/login/LoginDoctor.js
  src/pages/login/Login.js
  src/pages/pacient/login/LoginPacient.js
  src/pages/pacient/registration/RegistrationPacient.js
  src/pages/patient/logged/patientLogged.js
  src/pages/patient/logged/patientLogged.module.css
  src/pages/patient/logged/timeSlotsList/timeSlotsList.js
  src/pages/patient/registration/RegistrationPatient.js
  src/services/Auth.js
Labels: mergable

#20 #67, certificates
  src/components/patient/DataCertificate.js
  src/components/patient/SidebarData.js
  src/pages/patient/logged/certificates/certificates.js
  src/pages/patient/logged/patientLogged.js
  src/pages/patient/logged/timeSlotsList/timeSlotsList.js
Labels: mergable

#21 added doctor Time Slots + front incoming appointments (no backend)
  .gitignore
  src/Services.js
  src/components/doctor/DataIncomingAppointment.js
  src/components/doctor/SidebarData.js
  src/pages/doctor/logged/doctorLogged.js
  src/pages/doctor/logged/doctorTimeSlots/doctorTimeSlots.js
  src/pages/doctor/logged/doctorTimeSlots/timeSlot.module.css
  src/pages/doctor/logged/incomingAppointmentList/incomingAppointmentList.js
Labels: review me

#25 Patient delete inc appointment
  src/pages/patient/logged/incomingAppointments/incomingAppointmentsList.js
Labels: review me

#26 Fix patient and doctor appointments
  src/components/DataFormerAppointment.js
  src/components/patient/DataFormerAppointments.js
  src/pages/doctor/logged/appointmentList/DoctorAppointmentList.js
  src/pages/doctor/logged/doctorTimeSlots/timeSlot.module.css
Labels: review me

#22 Time slots filter
  src/components/patient/TimeSlotInfo.js
  src/pages/patient/logged/timeSlotsList/FilterForm.js
  src/pages/patient/logged/timeSlotsList/timeSlotsList.js
Labels: mergable

#23 #16 reserve timeslot
  src/components/patient/TimeSlotReserve.js
  src/pages/patient/logged/timeSlotsList/timeSlotsList.js
Labels: mergable

#29 Workflow dev
  .github/workflows/node.js.yml
  src/components/__tests__/AdminDoctorList.test.js
  src/components/__tests__/AdminNavigator.test.js
  src/components/__tests__/AdminPatientList.test.js
  src/components/__tests__/DoctorAppointmentList.test.js
Labels: mergable
