Repository io2-2022-JKL/team_L_frontend, pull requests merged in 2022-03, with the labels that each got.

#1 #9, pacient login page
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Forms/LoginForm.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/pacient/login/LoginPacient.js
  src/pages/pacient/login/LoginPacient.module.css
Labels: review me

#5 Change folder name
  src/forms/AuthorizationForm.module.css
  src/forms/LoginForm.js
  src/forms/RegistrationPacientForm.js
Labels: done

#3 #45, add registration page for pacient
  src/App.js
  src/forms/AuthorizationForm.module.css
  src/forms/LoginForm.js
  src/forms/RegistrationPacientForm.js
  src/pages/doctor/login/LoginDoctor.js
  src/pages/pacient/login/LoginPacient.js
  src/pages/pacient/registration/RegistrationPacient.js
Labels: done

#4 added admin login page
  src/App.js
  src/forms/LoginForm.js
  src/pages/admin/login/LoginAdmin.js
  src/pages/pacient/login/LoginPacient.js
Labels: mergable
